name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "**.spec.js"
      - ".idea"
      - ".vscode"
      - ".dockerignore"
      - "Dockerfile"
      - ".gitignore"
      - ".github/**"
      - "!.github/workflows/build.yml"

      
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # M1/ARM64 构建
          - os: macos-13
            arch: arm64
            target: mac-arm64

          # Intel/x64 构建
          - os: macos-12
            arch: x64
            target: mac-x64

          # Windows 构建
          - os: windows-2022
            arch: x64
            target: win-x64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Release Files
        timeout-minutes: 30
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ELECTRON_BUILD_ARCH: ${{ matrix.arch }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release_on_${{ matrix.target }}
          path: release/
          retention-days: 5
